name: Build package
on: 
  push: 
    branches: [ alphabuild ]
  release:
    types: [ published ]
  workflow_call:
    # inputs:
    #   branch:
    #     required: true
    #     type: string

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          repository: sygao/virtool-cli
          ref: ${{ github.ref_name }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build
        run: poetry build

      - uses: actions/upload-artifact@v3
        with:
          name: virtool-wheel
          path: dist/virtool_cli-2.0.0b1-py3-none-any.whl