name: Build package
on: 
  push: 
    branches: [ alphabuild ]
  release:
    types: [ published ]
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          repository: sygao/virtool-cli
          ref: ${{ github.ref_name }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local  # the path depends on the OS
          key: poetry-0  # increment to reset cache

      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1

      - name: Build
        run: poetry build

      - uses: actions/upload-artifact@v3
        with:
          name: virtool-wheel
          path: dist/virtool_cli-2.0.0b1-py3-none-any.whl