name: Build package
on: 
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-buster
    
    steps:
      - uses: actions/checkout@v3
        with:
          repository: sygao/virtool-cli
          ref: ${{ inputs.branch }}
          
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build
        run: poetry build

      - uses: actions/upload-artifact@v3
        with:
          name: virtool-wheel
          path: dist/virtool_cli-2.0.0b1-py3-none-any.whl