name: ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3:latest
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1

    steps:
      - uses: actions/checkout@v3

      - name: Install conda and poetry
        run: |
          conda install -c bioconda cd-hit hmmer blast mcl muscle -q -y
          pip install poetry
          
      - name: Install package
        run: |
          poetry lock
          poetry install
      
      - name: Run tests
        run: |
          echo $CALLER_API_URL
          poetry run pytest
        env:
          CALLER_API_URL: "${{ vars.CALLER_API_URL }}"
          GH_PAT: "${{ secrets.GH_BOT_PAT }}"
      
  release:
    if: github.event_name == 'push'
    needs:
      - test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install semantic-release
        run: npm i semantic-release@v18.0.0 conventional-changelog-conventionalcommits@4.6.1
      - name: Release
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release