name: Run tests
on:
  workflow_dispatch:
    inputs:
      ncbi:
        description: 'Test NCBI server fetches'
        type: boolean
        default: false

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    name: Runs tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-0
      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
      - name: Install packages
        run: poetry install
      - name: Test non-NCBI
        run: poetry run pytest -m "not ncbi" --disable-socket --allow-unix-socket
      - name: Test NCBI
        if: inputs.ncbi == true
        run: poetry run pytest -m "ncbi"
        env:
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
          NCBI_EMAIL: ${{ secrets.NCBI_EMAIL }}